require('dotenv').config();
const { remote } = require('webdriverio');
const assert = require('assert');

const APP_PACKAGE = 'com.metadevzone.hisabkitab360';
const APP_PATH = 'C:\\Users\\Meta Logix\\Downloads\\Hisab_Kitab_360_1.0.13.apk';

const OWNER_EMAIL = process.env.OWNER_EMAIL;
const OWNER_PASSWORD = process.env.OWNER_PASSWORD;
const COMPANY_EMAIL = process.env.COMPANY_EMAIL;
const COMPANY_PASSWORD = process.env.COMPANY_PASSWORD;
const STAFF_EMAIL = process.env.STAFF_EMAIL;
const STAFF_PASSWORD = process.env.STAFF_PASSWORD;

// Fixed identities discovered while exploring this account's data - not generated by the tests.
const OWNER_COMPANY_NAME = 'CMS';
const SUB_COMPANY_1 = 'irfan ORG'; // this is also COMPANY_EMAIL's own company
const SUB_COMPANY_2 = 'Nikolaus - Denesik'; // this is also STAFF_EMAIL's assigned company
const EXISTING_CUSTOMER = 'Royal Customer';

const capabilities = {
  platformName: 'Android',
  'appium:deviceName': 'Pixel_6',
  'appium:udid': '18271FDF600ATB',
  'appium:automationName': 'UiAutomator2',
  'appium:app': APP_PATH,
  'appium:noReset': true,
  'appium:autoGrantPermissions': true,
  'appium:newCommandTimeout': 240,
  'appium:androidInstallTimeout': 300000,
  'appium:uiautomator2ServerLaunchTimeout': 90000,
  'appium:uiautomator2ServerInstallTimeout': 90000,
  'appium:adbExecTimeout': 90000,
};

let driver;

// ---------- Locators ----------
const welcomeLoginButton = () => driver.$('~LOGIN'); // welcome nav button and the login-form submit button share this accessibility id
const loginEmailField = () => driver.$('//android.widget.EditText[@hint="Enter your email"]');
const loginPasswordField = () => driver.$('//android.widget.EditText[@hint="Enter your password"]');

const selectCompanySearchField = () => driver.$('//android.widget.EditText[@hint="Search companies..."]');
const cannotSwitchError = () => driver.$('android=new UiSelector().textContains("cannot switch companies")');

const dashboardProductsShortcut = () => driver.$('~Products');
const homeTab = () => driver.$('~Home');
const profileTab = () => driver.$('~Profile');

const addCompanyButton = () => driver.$('~Add Company');
const companyNameField = () => driver.$('//android.widget.EditText[@hint="Enter company name"]');
const companyEmailField = () => driver.$('//android.widget.EditText[@hint="Enter email address"]');
const companyPasswordField = () => driver.$('//android.widget.EditText[@hint="Enter password"]');
const companyActiveToggle = () => driver.$('~Active');
const companyInactiveToggle = () => driver.$('~Inactive');
const companySaveButton = () => driver.$('~Save');

const addStaffButton = () => driver.$('android=new UiSelector().textContains("Add Staff")');
const staffSearchField = () => driver.$('//android.widget.EditText[@hint="Search Here..."]');

const selectProductSearchField = () => driver.$('//android.widget.EditText[@hint="Select product"]');
const receivedAmountField = () => driver.$('//android.widget.EditText[@hint="0.00"]');
const KNOWN_PRODUCT = 'QA_PackUnit_Fixture';
const KNOWN_SUPPLIER = 'SHOP 1';

function el(text) {
  return driver.$(`android=new UiSelector().text("${text}")`);
}
// List rows only (TextView) - the search box (EditText) echoes the same text after typing a term.
function rowEl(text) {
  return driver.$(`android=new UiSelector().text("${text}").className("android.widget.TextView")`);
}
function elContains(text) {
  return driver.$(`android=new UiSelector().textContains("${text}")`);
}

// ---------- Core navigation helpers ----------

async function ensureLoggedOut() {
  await driver.terminateApp(APP_PACKAGE);
  await driver.activateApp(APP_PACKAGE);
  const onWelcome = await welcomeLoginButton().waitForDisplayed({ timeout: 8000 }).catch(() => false);
  if (onWelcome) return;

  // Something is logged in from a previous test - wipe app data for a clean, deterministic start.
  await driver.execute('mobile: clearApp', { appId: APP_PACKAGE });
  // clearApp revokes runtime permissions; the camera prompt would otherwise pop up over the
  // barcode-enabled Select Product screen and swallow taps.
  await driver
    .execute('mobile: changePermissions', {
      action: 'grant',
      appPackage: APP_PACKAGE,
      permissions: ['android.permission.CAMERA'],
    })
    .catch(() => {});
  await driver.activateApp(APP_PACKAGE);
  await welcomeLoginButton().waitForDisplayed({ timeout: 15000 });
}

async function dismissCameraPrompt() {
  const allowCamera = el('While using the app');
  if (await allowCamera.isDisplayed().catch(() => false)) await allowCamera.click();
}

async function fillLoginForm(email, password) {
  await welcomeLoginButton().click();
  await loginEmailField().waitForDisplayed({ timeout: 10000 });
  await loginEmailField().setValue(email);
  await loginPasswordField().setValue(password);
  await welcomeLoginButton().click();
}

async function selectCompanyByName(name) {
  await selectCompanySearchField().waitForDisplayed({ timeout: 10000 });
  const row = el(name);
  await row.waitForDisplayed({ timeout: 10000 });
  await row.click();
}

// Logs out, logs back in as the given account, and - if the Select Company screen appears -
// picks the given company. Waits until the dashboard is reachable.
async function loginAndSelectCompany(email, password, companyName) {
  await ensureLoggedOut();
  await fillLoginForm(email, password);
  const onSelectCompany = await selectCompanySearchField().waitForDisplayed({ timeout: 10000 }).catch(() => false);
  if (onSelectCompany) {
    await selectCompanyByName(companyName);
  }
  await dashboardProductsShortcut().waitForDisplayed({ timeout: 20000 });
}

async function openDrawer() {
  await driver.execute('mobile: clickGesture', { x: 43, y: 173 });
  await driver.pause(500);
}

// Uses UiAutomator's native scrollIntoView against the drawer's scrollable container -
// far more reliable than manual swipe-and-check loops for a long, deeply nested menu.
async function drawerTap(text) {
  const locator = driver.$(
    `android=new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().textContains("${text}").instance(0))`
  );
  await locator.waitForDisplayed({ timeout: 10000 });
  await locator.click();
}

async function goToCompaniesScreen() {
  await loginAndSelectCompany(OWNER_EMAIL, OWNER_PASSWORD, OWNER_COMPANY_NAME);
  await openDrawer();
  await drawerTap('Companies');
  await addCompanyButton().waitForDisplayed({ timeout: 10000 });
}

// The Companies list grows with every test run - search to isolate a specific
// row before interacting with it, rather than assuming it is on-screen unfiltered.
async function searchOnCompaniesScreen(term) {
  const field = selectCompanySearchField(); // shares the same hint as the Select Company screen
  const alreadyThere = await field.waitForDisplayed({ timeout: 8000 }).catch(() => false);
  if (!alreadyThere) {
    // Saving sometimes lands somewhere other than the list - re-navigate to it fresh.
    await openDrawer();
    await drawerTap('Companies');
    await field.waitForDisplayed({ timeout: 15000 });
  }
  await field.clearValue().catch(() => {});
  await field.setValue(term);
  await driver.pause(1200);
  // The keyboard stays open after typing - the first tap on a row's 3-dot menu
  // just dismisses it instead of opening the menu, so close it explicitly here.
  await driver.execute('mobile: hideKeyboard').catch(() => {});
}

// The plan allows only a handful of extra companies, so every test that creates one
// must remove it again or later tests hit "Plan Limit Exceeded".
async function deleteCompanyByName(name) {
  try {
    await searchOnCompaniesScreen(name);
  } catch (e) {
    // Some forms (e.g. Change Password) land somewhere other than the list - start fresh.
    await goToCompaniesScreen();
    await searchOnCompaniesScreen(name);
  }
  await openRowContextMenu(name, 'Delete');
  const confirmYes = driver.$('~Yes');
  const hasConfirm = await confirmYes.waitForDisplayed({ timeout: 4000 }).then(() => true).catch(() => false);
  if (hasConfirm) await confirmYes.click();
  await driver.pause(2000);
}

// Tapping the "Allow to Login" label opens Staff Details - the actual checkbox sits just left of it.
async function toggleAllowToLogin() {
  const label = elContains('Allow to Login');
  await label.waitForDisplayed({ timeout: 10000 });
  const loc = await label.getLocation();
  await driver.execute('mobile: clickGesture', { x: Math.round(loc.x) - 34, y: Math.round(loc.y) + 15 });
  const confirmYes = driver.$('~Yes');
  if (await confirmYes.waitForDisplayed({ timeout: 2500 }).catch(() => false)) await confirmYes.click();
  await driver.pause(2000);
}

async function goToStaffScreen() {
  await loginAndSelectCompany(OWNER_EMAIL, OWNER_PASSWORD, OWNER_COMPANY_NAME);
  await openDrawer();
  await drawerTap('HRM');
  await drawerTap('Staff');
  await addStaffButton().waitForDisplayed({ timeout: 10000 });
}

// Opens the "Switch Company" bottom sheet from the Home dropdown header.
async function openSwitchCompanySheet() {
  await driver.execute('mobile: clickGesture', { x: 540, y: 350 });
  await el('Switch Company').waitForDisplayed({ timeout: 10000 });
}

// Finds a list row by its visible text, taps the 3-dot menu to its right, then taps
// the named menu option. Mirrors the row-icon pattern used in brand.test.js / product.test.js.
async function openRowContextMenu(rowText, menuOptionText) {
  await driver.execute('mobile: hideKeyboard').catch(() => {});
  const row = rowEl(rowText);
  await row.waitForDisplayed({ timeout: 10000 });
  const loc = await row.getLocation();
  const option = el(menuOptionText);
  let menuOpen = false;
  for (let attempt = 0; attempt < 3 && !menuOpen; attempt++) {
    await driver.execute('mobile: clickGesture', { x: 999, y: Math.round(loc.y) + 26 });
    menuOpen = await option.waitForDisplayed({ timeout: 4000 }).catch(() => false);
  }
  if (!menuOpen) {
    throw new Error(`Could not open the row context menu for "${rowText}" (looking for "${menuOptionText}")`);
  }
  await option.click();
}

function uniqueName(prefix) {
  return `${prefix}_${Date.now()}`;
}

// Taps "Add Product" on an open Add Invoice / Add Shipment form, picks a product from the
// search results, and confirms the line item via "Add Item". Leaves the caller back on the
// parent form with the product line added.
async function addProductLineToForm(productName) {
  const addProductBtn = driver.$('~Add Product');
  await addProductBtn.waitForDisplayed({ timeout: 15000 });

  // Tapping this has proven flaky (native .click() and coordinate taps both
  // occasionally no-op) - retry a few times rather than trusting a single attempt.
  let onSelectProduct = false;
  for (let attempt = 0; attempt < 3 && !onSelectProduct; attempt++) {
    const loc = await addProductBtn.getLocation();
    const size = await addProductBtn.getSize();
    await driver.execute('mobile: clickGesture', {
      x: Math.round(loc.x + size.width / 2),
      y: Math.round(loc.y + size.height / 2),
    });
    await dismissCameraPrompt();
    onSelectProduct = await selectProductSearchField().waitForDisplayed({ timeout: 7000 }).catch(() => false);
  }
  if (!onSelectProduct) {
    throw new Error('Could not reach the Select Product screen after retrying "Add Product"');
  }

  await selectProductSearchField().setValue(productName);
  await driver.pause(1500);
  await el(productName).waitForDisplayed({ timeout: 10000 });
  await driver.execute('mobile: hideKeyboard').catch(() => {});

  // The Select Product screen has its own always-visible "Add Item" footer (it creates a
  // brand-new product), so success here means we LEFT that screen, not that "Add Item" exists.
  const productRow = driver.$(`android=new UiSelector().descriptionContains("${productName}")`);
  let onProductDetail = false;
  for (let attempt = 0; attempt < 4 && !onProductDetail; attempt++) {
    await dismissCameraPrompt();
    await productRow.click().catch(() => {});
    await driver.pause(1500);
    await dismissCameraPrompt();
    const stillOnList = await selectProductSearchField().isDisplayed().catch(() => false);
    onProductDetail = !stillOnList;
  }
  if (!onProductDetail) {
    throw new Error('Could not open the product detail after retrying product selection');
  }

  await driver.$('~Add Item').waitForDisplayed({ timeout: 10000 });
  await driver.$('~Add Item').click();
  await driver.pause(1000);
}

describe('Hisab Kitab 360 - Multi-Company (Owner / Company / Staff)', function () {
  this.timeout(180000);

  before(async () => {
    driver = await remote({
      protocol: 'http',
      hostname: '127.0.0.1',
      port: 4723,
      path: '/',
      connectionRetryTimeout: 300000,
      connectionRetryCount: 1,
      capabilities,
    });
  });

  after(async () => {
    if (driver) await driver.deleteSession();
  });

  // ================= A. Login & Select Company =================

  it('TC01: Owner login par Select Company screen CMS(Owner) + dono sub-companies dikhati hai', async () => {
    await ensureLoggedOut();
    await fillLoginForm(OWNER_EMAIL, OWNER_PASSWORD);
    await selectCompanySearchField().waitForDisplayed({ timeout: 10000 });
    assert.ok(await el(OWNER_COMPANY_NAME).isDisplayed());
    assert.ok(await el(SUB_COMPANY_1).isDisplayed());
    assert.ok(await el(SUB_COMPANY_2).isDisplayed());
  });

  it('TC02: Owner "CMS" select karta hai to apna dashboard khulta hai', async () => {
    await loginAndSelectCompany(OWNER_EMAIL, OWNER_PASSWORD, OWNER_COMPANY_NAME);
    assert.ok(await dashboardProductsShortcut().isDisplayed());
  });

  it('TC03: Owner sub-company "irfan ORG" select karta hai to uska dashboard khulta hai', async () => {
    await loginAndSelectCompany(OWNER_EMAIL, OWNER_PASSWORD, SUB_COMPANY_1);
    assert.ok(await dashboardProductsShortcut().isDisplayed());
    assert.ok(await elContains(SUB_COMPANY_1).isDisplayed());
  });

  it('TC04: Owner sub-company "Nikolaus - Denesik" select karta hai to uska dashboard khulta hai', async () => {
    await loginAndSelectCompany(OWNER_EMAIL, OWNER_PASSWORD, SUB_COMPANY_2);
    assert.ok(await dashboardProductsShortcut().isDisplayed());
  });

  it('TC05: Company login par Select Company sirf apni company dikhati hai', async () => {
    await ensureLoggedOut();
    await fillLoginForm(COMPANY_EMAIL, COMPANY_PASSWORD);
    await selectCompanySearchField().waitForDisplayed({ timeout: 10000 });
    assert.ok(await el(SUB_COMPANY_1).isDisplayed());
  });

  it('TC06 [BUG]: Company login apni (sirf) company select karta hai to error aata hai aur stuck reh jata hai', async () => {
    await ensureLoggedOut();
    await fillLoginForm(COMPANY_EMAIL, COMPANY_PASSWORD);
    await selectCompanySearchField().waitForDisplayed({ timeout: 10000 });
    await el(SUB_COMPANY_1).click();
    await cannotSwitchError().waitForDisplayed({ timeout: 5000 });
    assert.ok(await cannotSwitchError().isDisplayed());
    // Documents the bug: the dashboard should NOT be reachable this way.
    const reachedDashboard = await dashboardProductsShortcut().isDisplayed().catch(() => false);
    assert.strictEqual(reachedDashboard, false, 'Unexpected: dashboard became reachable - bug may be fixed, update this test');
  });

  it('TC07: Staff login par Select Company assigned company dikhati hai (ya seedha dashboard, agar sirf 1 hi company hai)', async () => {
    await ensureLoggedOut();
    await fillLoginForm(STAFF_EMAIL, STAFF_PASSWORD);
    // With only one assigned company, the app sometimes skips the picker and goes
    // straight to the dashboard instead of showing "Select Company" - both are valid.
    const onSelectCompany = await selectCompanySearchField().waitForDisplayed({ timeout: 25000 }).catch(() => false);
    if (onSelectCompany) {
      assert.ok(await el(SUB_COMPANY_2).isDisplayed());
    } else {
      assert.ok(await dashboardProductsShortcut().waitForDisplayed({ timeout: 15000 }));
    }
  });

  it('TC08: Staff assigned company select karta hai to successfully dashboard tak pohonchta hai', async () => {
    await loginAndSelectCompany(STAFF_EMAIL, STAFF_PASSWORD, SUB_COMPANY_2);
    assert.ok(await dashboardProductsShortcut().isDisplayed());
  });

  // ================= B. Account Switching (Home dropdown) =================

  it('TC09: Home ka top dropdown current company ka naam dikhata hai', async () => {
    await loginAndSelectCompany(OWNER_EMAIL, OWNER_PASSWORD, OWNER_COMPANY_NAME);
    assert.ok(await elContains(OWNER_COMPANY_NAME).isDisplayed());
  });

  it('TC10: Dropdown tap karne se "Switch Company" sheet khulti hai', async () => {
    await loginAndSelectCompany(OWNER_EMAIL, OWNER_PASSWORD, OWNER_COMPANY_NAME);
    await openSwitchCompanySheet();
    assert.ok(await el(SUB_COMPANY_1).isDisplayed());
    assert.ok(await el(SUB_COMPANY_2).isDisplayed());
  });

  it('TC11: Owner sheet se doosri company select karta hai to dashboard context change hota hai', async () => {
    await loginAndSelectCompany(OWNER_EMAIL, OWNER_PASSWORD, OWNER_COMPANY_NAME);
    await openSwitchCompanySheet();
    await el(SUB_COMPANY_1).click();
    await driver.pause(2000);
    assert.ok(await elContains(SUB_COMPANY_1).isDisplayed());
  });

  it('TC12: Switch Company sheet X se band ho jati hai, company change nahi hoti', async () => {
    await loginAndSelectCompany(OWNER_EMAIL, OWNER_PASSWORD, OWNER_COMPANY_NAME);
    await openSwitchCompanySheet();
    await driver.execute('mobile: clickGesture', { x: 853, y: 1584 });
    await driver.pause(1000);
    assert.ok(await elContains(OWNER_COMPANY_NAME).isDisplayed());
  });

  // ================= C. Company Management (CRUD) =================

  it('TC13: Companies list mein CMS, irfan ORG, aur Nikolaus - Denesik dikhte hain', async () => {
    await goToCompaniesScreen();
    assert.ok(await el(OWNER_COMPANY_NAME).isDisplayed());
    assert.ok(await el(SUB_COMPANY_1).isDisplayed());
    assert.ok(await el(SUB_COMPANY_2).isDisplayed());
  });

  it('TC14: Valid data se naya Company add hota hai', async () => {
    await goToCompaniesScreen();
    const name = uniqueName('QA_Company');
    await addCompanyButton().click();
    await companyNameField().waitForDisplayed({ timeout: 10000 });
    await companyNameField().setValue(name);
    await companyEmailField().setValue(`${name.toLowerCase()}@example.com`);
    await companyPasswordField().setValue('Passw0rd123');
    await companySaveButton().click();
    await driver.waitUntil(async () => !(await companyNameField().isDisplayed().catch(() => false)), { timeout: 15000 });
    assert.ok(await rowEl(name).isDisplayed());
    await deleteCompanyByName(name).catch((e) => console.log('cleanup failed:', e.message));
  });

  it('TC15: Empty required fields ke sath Add Company submit karne par validation error', async () => {
    await goToCompaniesScreen();
    await addCompanyButton().click();
    await companyNameField().waitForDisplayed({ timeout: 10000 });
    await companySaveButton().click();
    await driver.pause(2000);
    assert.ok(await companyNameField().isDisplayed(), 'Expected to remain on the Add Company form');
  });

  it('TC16: Company ka naam edit karne se list mein reflect hota hai', async () => {
    await goToCompaniesScreen();
    const original = uniqueName('QA_Company_Edit');
    await addCompanyButton().click();
    await companyNameField().waitForDisplayed({ timeout: 10000 });
    await companyNameField().setValue(original);
    await companyEmailField().setValue(`${original.toLowerCase()}@example.com`);
    await companyPasswordField().setValue('Passw0rd123');
    await companySaveButton().click();
    await driver.waitUntil(async () => !(await companyNameField().isDisplayed().catch(() => false)), { timeout: 15000 });

    await searchOnCompaniesScreen(original);
    const updated = original + '_Updated';
    await openRowContextMenu(original, 'Edit');
    await companyNameField().waitForDisplayed({ timeout: 10000 });
    await companyNameField().clearValue().catch(() => {});
    await companyNameField().setValue(updated);
    await companySaveButton().click();
    await driver.waitUntil(async () => !(await companyNameField().isDisplayed().catch(() => false)), { timeout: 15000 });
    await searchOnCompaniesScreen(updated);
    assert.ok(await rowEl(updated).isDisplayed());
    await deleteCompanyByName(updated).catch((e) => console.log('cleanup failed:', e.message));
  });

  it('TC17: Company ka password change hota hai', async () => {
    await goToCompaniesScreen();
    const name = uniqueName('QA_Company_Pwd');
    await addCompanyButton().click();
    await companyNameField().waitForDisplayed({ timeout: 10000 });
    await companyNameField().setValue(name);
    await companyEmailField().setValue(`${name.toLowerCase()}@example.com`);
    await companyPasswordField().setValue('Passw0rd123');
    await companySaveButton().click();
    await driver.waitUntil(async () => !(await companyNameField().isDisplayed().catch(() => false)), { timeout: 15000 });

    await searchOnCompaniesScreen(name);
    await openRowContextMenu(name, 'Change Password');
    const newPwdField = driver.$('//android.widget.EditText[@hint="Enter password"]');
    await newPwdField.waitForDisplayed({ timeout: 10000 });
    await newPwdField.setValue('NewPassw0rd456');
    await companySaveButton().click();
    await driver.pause(2000);
    const state = await driver.queryAppState(APP_PACKAGE);
    assert.strictEqual(state, 4, `Expected app to still be running in foreground, got state ${state}`);
    await deleteCompanyByName(name).catch((e) => console.log('cleanup failed:', e.message));
  });

  it('TC18: Company Deactivate karna successfully hota hai', async () => {
    await goToCompaniesScreen();
    const name = uniqueName('QA_Company_Deactivate');
    await addCompanyButton().click();
    await companyNameField().waitForDisplayed({ timeout: 10000 });
    await companyNameField().setValue(name);
    await companyEmailField().setValue(`${name.toLowerCase()}@example.com`);
    await companyPasswordField().setValue('Passw0rd123');
    await companySaveButton().click();
    await driver.waitUntil(async () => !(await companyNameField().isDisplayed().catch(() => false)), { timeout: 15000 });

    await searchOnCompaniesScreen(name);
    await openRowContextMenu(name, 'Deactivate');
    await driver.pause(2000);
    const state = await driver.queryAppState(APP_PACKAGE);
    assert.strictEqual(state, 4, `Expected app to still be running in foreground, got state ${state}`);
    await deleteCompanyByName(name).catch((e) => console.log('cleanup failed:', e.message));
  });

  it('TC19: Naya banaya gaya Company Delete karne se list se hat jata hai', async () => {
    await goToCompaniesScreen();
    const name = uniqueName('QA_Company_Delete');
    await addCompanyButton().click();
    await companyNameField().waitForDisplayed({ timeout: 10000 });
    await companyNameField().setValue(name);
    await companyEmailField().setValue(`${name.toLowerCase()}@example.com`);
    await companyPasswordField().setValue('Passw0rd123');
    await companySaveButton().click();
    await driver.waitUntil(async () => !(await companyNameField().isDisplayed().catch(() => false)), { timeout: 15000 });

    await searchOnCompaniesScreen(name);
    assert.ok(await rowEl(name).isDisplayed());

    await openRowContextMenu(name, 'Delete');
    const confirmYes = driver.$('~Yes');
    const hasConfirm = await confirmYes.waitForDisplayed({ timeout: 4000 }).then(() => true).catch(() => false);
    if (hasConfirm) await confirmYes.click();
    await driver.pause(2000);
    const stillThere = await rowEl(name).isDisplayed().catch(() => false);
    assert.strictEqual(stillThere, false, 'Expected the deleted company to no longer be listed');
  });

  // ================= D. Manage Nav Items (Company permissions) =================

  it('TC20: Company ke liye "Manage Nav Items" kholne par module checklist dikhti hai', async () => {
    await goToCompaniesScreen();
    await openRowContextMenu(SUB_COMPANY_1, 'Manage Nav Items');
    assert.ok(await el('Select All').isDisplayed());
    assert.ok(await el('Dashboard').isDisplayed());
    assert.ok(await el('Products').isDisplayed());
  });

  it('TC21: "Select All" tap karne se sab modules check ho jate hain', async () => {
    await goToCompaniesScreen();
    await openRowContextMenu(SUB_COMPANY_1, 'Manage Nav Items');
    await el('Select All').waitForDisplayed({ timeout: 10000 });
    await el('Select All').click();
    await driver.pause(1000);
    const state = await driver.queryAppState(APP_PACKAGE);
    assert.strictEqual(state, 4, `Expected app to still be running in foreground, got state ${state}`);
  });

  it('TC22: Specific modules select kar ke Save karna successful hota hai', async () => {
    await goToCompaniesScreen();
    await openRowContextMenu(SUB_COMPANY_1, 'Manage Nav Items');
    await el('Dashboard').waitForDisplayed({ timeout: 10000 });
    await el('Dashboard').click();
    await el('Products').click();
    await el('Save').click();
    await driver.pause(2000);
    const state = await driver.queryAppState(APP_PACKAGE);
    assert.strictEqual(state, 4, `Expected app to still be running in foreground, got state ${state}`);
  });

  // ================= E. HRM Staff & Company Assignment =================

  it('TC23: Staff list mein entries "Allow to Login" toggle ke sath dikhti hain', async () => {
    await goToStaffScreen();
    await staffSearchField().waitForDisplayed({ timeout: 10000 });
    await staffSearchField().setValue('irfan');
    await driver.pause(1500);
    assert.ok(await elContains('irfan Naseer').isDisplayed());
    assert.ok(await el('Allow to Login').isDisplayed());
  });

  it('TC24: Valid data se naya Staff add hota hai', async () => {
    await goToStaffScreen();
    const first = uniqueName('QAStaff');
    await addStaffButton().click();
    const firstNameField = driver.$('//android.widget.EditText[@hint="Enter first name"]');
    await firstNameField.waitForDisplayed({ timeout: 10000 });
    await firstNameField.setValue(first);
    await driver.$('//android.widget.EditText[@hint="Enter last name"]').setValue('Tester');
    await driver.$('//android.widget.EditText[@hint="Enter email address"]').setValue(`${first.toLowerCase()}@example.com`);
    await driver.$('//android.widget.EditText[@hint="Enter password"]').setValue('Passw0rd123');
    await driver.$('//android.widget.EditText[@hint="Enter basic salary"]').setValue('15000');
    await driver.$('//android.widget.EditText[@hint="Enter gross salary"]').setValue('17000');

    await driver.$('//android.widget.EditText[@hint="Select joining date"]').click();
    await el('Confirm').waitForDisplayed({ timeout: 5000 });
    await el('Confirm').click();

    await el('Submit').click();
    await driver.pause(3000);
    const staffSearch = staffSearchField();
    await staffSearch.waitForDisplayed({ timeout: 10000 });
    await staffSearch.setValue(first);
    await driver.pause(1500);
    assert.ok(await elContains(first).isDisplayed());
  });

  it('TC25: Add Staff required field khali chorne par validation error', async () => {
    await goToStaffScreen();
    await addStaffButton().click();
    const submitBtn = el('Submit');
    await submitBtn.waitForDisplayed({ timeout: 10000 });
    await submitBtn.click();
    await driver.pause(2000);
    const state = await driver.queryAppState(APP_PACKAGE);
    assert.strictEqual(state, 4, `Expected app to still be running in foreground, got state ${state}`);
  });

  it('TC26: Edit Staff mein "Assign Companies" se company add hoti hai', async () => {
    await goToStaffScreen();
    await staffSearchField().waitForDisplayed({ timeout: 10000 });
    await staffSearchField().setValue('irfan');
    await driver.pause(1500);
    await openRowContextMenu('irfan Naseer', 'Edit');
    assert.ok(await elContains('Assign Companies').isDisplayed());
    assert.ok(await el(SUB_COMPANY_2).isDisplayed());
  });

  it('TC27: Assigned company chip X se remove hoti hai', async () => {
    await goToStaffScreen();
    await staffSearchField().waitForDisplayed({ timeout: 10000 });
    await staffSearchField().setValue('irfan');
    await driver.pause(1500);
    await openRowContextMenu('irfan Naseer', 'Edit');
    const assignedRow = el(SUB_COMPANY_2);
    await assignedRow.waitForDisplayed({ timeout: 10000 });
    const loc = await assignedRow.getLocation();
    await driver.execute('mobile: clickGesture', { x: 723, y: Math.round(loc.y) });
    await driver.pause(1000);
    const stillAssigned = await el(SUB_COMPANY_2).isDisplayed().catch(() => false);
    console.log(stillAssigned ? 'Company chip still present (remove may need Save)' : 'Company chip removed from the field');
  });

  it('TC28: Staff ka "Allow to Login" off karne se uska login block ho jana chahiye', async () => {
    await goToStaffScreen();
    await staffSearchField().waitForDisplayed({ timeout: 10000 });
    await staffSearchField().setValue('irfan');
    await driver.pause(1500);
    await driver.execute('mobile: hideKeyboard').catch(() => {});
    await toggleAllowToLogin();
    // Restore the toggle so subsequent staff-login tests are not affected.
    await toggleAllowToLogin();
    assert.ok(await elContains('irfan Naseer').isDisplayed(), 'Expected to remain on the Staff list after toggling');
  });

  it('TC29: "Manage Staff NavItems" module checklist dikhti hai', async () => {
    await goToStaffScreen();
    await staffSearchField().waitForDisplayed({ timeout: 10000 });
    await staffSearchField().setValue('irfan');
    await driver.pause(1500);
    await openRowContextMenu('irfan Naseer', 'Manage Staff NavItems');
    assert.ok(await el('Dashboard').isDisplayed());
  });

  // ================= F. Owner visibility into sub-company actions =================

  it('TC30: Staff ka record kiya hua Payment Owner ko us company mein dikhna chahiye', async () => {
    const paymentNote = uniqueName('QA_CrossTrack');

    await loginAndSelectCompany(STAFF_EMAIL, STAFF_PASSWORD, SUB_COMPANY_2);
    const paymentsShortcut = driver.$('~Payments');
    await paymentsShortcut.waitForDisplayed({ timeout: 10000 });
    await paymentsShortcut.click();
    const addPaymentBtn = driver.$('~Add Payment');
    await addPaymentBtn.waitForDisplayed({ timeout: 10000 });
    await addPaymentBtn.click();

    const customerField = el('Select customer');
    await customerField.waitForDisplayed({ timeout: 10000 });
    await customerField.click();
    await el(EXISTING_CUSTOMER).waitForDisplayed({ timeout: 10000 });
    await el(EXISTING_CUSTOMER).click();

    const amountField = driver.$('//android.widget.EditText[@hint="Enter amount"]');
    await amountField.setValue('123');
    const noteField = driver.$('//android.widget.EditText[@hint="Enter note"]');
    await noteField.setValue(paymentNote).catch(() => {});
    await el('Submit').click();
    await driver.pause(3000);

    await loginAndSelectCompany(OWNER_EMAIL, OWNER_PASSWORD, SUB_COMPANY_2);
    const ownerPaymentsShortcut = driver.$('~Payments');
    await ownerPaymentsShortcut.waitForDisplayed({ timeout: 10000 });
    await ownerPaymentsShortcut.click();
    const search = driver.$('//android.widget.EditText[@hint="Search..."]');
    await search.waitForDisplayed({ timeout: 10000 });
    await search.setValue(EXISTING_CUSTOMER);
    await driver.pause(1500);
    assert.ok(await elContains(EXISTING_CUSTOMER).isDisplayed());
  });

  // ================= G. Payment / Shipment operations =================

  it('TC31: Valid Customer + Amount se Payment successfully add hota hai', async () => {
    await loginAndSelectCompany(OWNER_EMAIL, OWNER_PASSWORD, OWNER_COMPANY_NAME);
    const paymentsShortcut = driver.$('~Payments');
    await paymentsShortcut.waitForDisplayed({ timeout: 10000 });
    await paymentsShortcut.click();
    await driver.$('~Add Payment').click();

    await el('Select customer').waitForDisplayed({ timeout: 10000 });
    await el('Select customer').click();
    await el(EXISTING_CUSTOMER).waitForDisplayed({ timeout: 10000 });
    await el(EXISTING_CUSTOMER).click();

    await driver.$('//android.widget.EditText[@hint="Enter amount"]').setValue('500');
    await el('Submit').click();
    await driver.pause(2000);
    const state = await driver.queryAppState(APP_PACKAGE);
    assert.strictEqual(state, 4, `Expected app to still be running in foreground, got state ${state}`);
  });

  it('TC32: Amount khali chor kar Payment submit karne par validation error', async () => {
    await loginAndSelectCompany(OWNER_EMAIL, OWNER_PASSWORD, OWNER_COMPANY_NAME);
    const paymentsShortcut = driver.$('~Payments');
    await paymentsShortcut.waitForDisplayed({ timeout: 10000 });
    await paymentsShortcut.click();
    await driver.$('~Add Payment').click();

    await el('Select customer').waitForDisplayed({ timeout: 10000 });
    await el('Select customer').click();
    await el(EXISTING_CUSTOMER).waitForDisplayed({ timeout: 10000 });
    await el(EXISTING_CUSTOMER).click();

    await el('Submit').click();
    await driver.pause(2000);
    const amountFieldStillThere = await driver.$('//android.widget.EditText[@hint="Enter amount"]').isDisplayed().catch(() => false);
    assert.ok(amountFieldStillThere, 'Expected to remain on the Add Payment form');
  });

  it('TC33: Customer picker search se sahi customer select hota hai', async () => {
    await loginAndSelectCompany(OWNER_EMAIL, OWNER_PASSWORD, OWNER_COMPANY_NAME);
    const paymentsShortcut = driver.$('~Payments');
    await paymentsShortcut.waitForDisplayed({ timeout: 10000 });
    await paymentsShortcut.click();
    await driver.$('~Add Payment').click();

    await el('Select customer').waitForDisplayed({ timeout: 10000 });
    await el('Select customer').click();
    const pickerSearch = driver.$('//android.widget.EditText[@hint="Search..."]');
    await pickerSearch.waitForDisplayed({ timeout: 10000 });
    await pickerSearch.setValue(EXISTING_CUSTOMER);
    await driver.pause(1000);
    await el(EXISTING_CUSTOMER).click();
    assert.ok(await elContains(EXISTING_CUSTOMER).isDisplayed());
  });

  it('TC34: Add Shipment bina product ke Save karne par validation blocked hoti hai', async () => {
    await loginAndSelectCompany(OWNER_EMAIL, OWNER_PASSWORD, OWNER_COMPANY_NAME);
    const shipmentsShortcut = driver.$('~Shipments');
    await shipmentsShortcut.waitForDisplayed({ timeout: 10000 });
    await shipmentsShortcut.click();
    await driver.$('~Add Shipment').click();

    const titleField = driver.$('//android.widget.EditText[@hint="Add your shipment title"]');
    await titleField.waitForDisplayed({ timeout: 10000 });
    await titleField.setValue(uniqueName('QA_Shipment'));
    await el('Save').click().catch(() => {});
    await driver.pause(2000);
    const stillOnForm = await titleField.isDisplayed().catch(() => false);
    assert.ok(stillOnForm, 'Expected shipment save to be blocked without a product line');
  });

  it('TC35: Valid Supplier + Product ke sath Shipment successfully add hoti hai', async () => {
    await loginAndSelectCompany(OWNER_EMAIL, OWNER_PASSWORD, OWNER_COMPANY_NAME);
    const shipmentsShortcut = driver.$('~Shipments');
    await shipmentsShortcut.waitForDisplayed({ timeout: 10000 });
    await shipmentsShortcut.click();
    await driver.$('~Add Shipment').click();

    const titleField = driver.$('//android.widget.EditText[@hint="Add your shipment title"]');
    await titleField.waitForDisplayed({ timeout: 10000 });
    await titleField.setValue(uniqueName('QA_Shipment'));

    // The Supplier field remembers the last-picked supplier across sessions - only open
    // the picker if it is still showing the empty placeholder.
    const supplierPlaceholder = el('Select...');
    if (await supplierPlaceholder.isDisplayed().catch(() => false)) {
      await supplierPlaceholder.click();
      await el(KNOWN_SUPPLIER).waitForDisplayed({ timeout: 10000 });
      await el(KNOWN_SUPPLIER).click();
    }

    await addProductLineToForm(KNOWN_PRODUCT);

    await el('Save & Exit').click();
    await driver.waitUntil(async () => !(await titleField.isDisplayed().catch(() => false)), {
      timeout: 15000,
      timeoutMsg: 'Expected to navigate away from the Add Shipment form after a successful save',
    });
  });

  it('TC36: Valid product ke sath POS Invoicing (Sale) successfully add hoti hai', async () => {
    await loginAndSelectCompany(OWNER_EMAIL, OWNER_PASSWORD, OWNER_COMPANY_NAME);
    const posShortcut = driver.$('~POS Invoicing');
    await posShortcut.waitForDisplayed({ timeout: 10000 });
    await posShortcut.click();
    await driver.$('~Add Invoice').click();

    await addProductLineToForm(KNOWN_PRODUCT);

    await receivedAmountField().waitForDisplayed({ timeout: 10000 });
    await receivedAmountField().setValue('100');
    await driver.execute('mobile: hideKeyboard').catch(() => {});

    await el('Save & Exit').click();
    await driver.waitUntil(async () => !(await receivedAmountField().isDisplayed().catch(() => false)), {
      timeout: 15000,
      timeoutMsg: 'Expected to navigate away from the Add Invoice form after a successful save',
    });
  });

  it('TC37 [BUG]: Sub-company context (irfan ORG) mein Sale save karne par "Business not found" error aata hai', async () => {
    await loginAndSelectCompany(OWNER_EMAIL, OWNER_PASSWORD, SUB_COMPANY_1);
    const posShortcut = driver.$('~POS Invoicing');
    await posShortcut.waitForDisplayed({ timeout: 10000 });
    await posShortcut.click();
    await driver.$('~Add Invoice').click();

    await addProductLineToForm(KNOWN_PRODUCT);

    await receivedAmountField().waitForDisplayed({ timeout: 10000 });
    await receivedAmountField().setValue('100');
    await driver.execute('mobile: hideKeyboard').catch(() => {});

    await el('Save & Exit').click();
    const businessNotFoundError = elContains('Business not found');
    await businessNotFoundError.waitForDisplayed({ timeout: 5000 });
    assert.ok(await businessNotFoundError.isDisplayed());
  });

  it('TC38: Companies Report Operational Reports mein locate karna (abhi skip - user ne skip karne ko kaha)', async function () {
    this.skip();
  });

  // ================= H. Deactivate / Delete Access Control =================
  // Verifies that disabling an account (Company Deactivate, Staff "Allow to Login" off)
  // or deleting it actually blocks that account's own login - not just that the
  // toggle/row visually changes. Also confirms deleted records leave the list.

  it('TC39: Deactivate ki gayi Company apne hi credentials se login karke dashboard tak nahi pohonch pati', async () => {
    await goToCompaniesScreen();
    const name = uniqueName('QA_Deactivate_Login');
    const email = `${name.toLowerCase()}@example.com`;
    const password = 'Passw0rd123';
    await addCompanyButton().click();
    await companyNameField().waitForDisplayed({ timeout: 10000 });
    await companyNameField().setValue(name);
    await companyEmailField().setValue(email);
    await companyPasswordField().setValue(password);
    await companySaveButton().click();
    await driver.waitUntil(async () => !(await companyNameField().isDisplayed().catch(() => false)), { timeout: 15000 });

    await searchOnCompaniesScreen(name);
    await openRowContextMenu(name, 'Deactivate');
    await driver.pause(2000);

    await ensureLoggedOut();
    await fillLoginForm(email, password);
    await driver.pause(3000);
    const reachedDashboard = await dashboardProductsShortcut().isDisplayed().catch(() => false);
    const onSelectCompany = await selectCompanySearchField().isDisplayed().catch(() => false);
    console.log(`TC39: after deactivating "${name}" and logging in with its own credentials - ` +
      `reachedDashboard=${reachedDashboard}, onSelectCompany=${onSelectCompany}`);

    await goToCompaniesScreen();
    await deleteCompanyByName(name).catch((e) => console.log('cleanup failed:', e.message));
    assert.strictEqual(reachedDashboard, false, 'A deactivated company should not be able to reach its dashboard');
  });

  it('TC40: Delete ki gayi Company apne credentials se login nahi kar pati aur list se bhi hat jati hai', async () => {
    await goToCompaniesScreen();
    const name = uniqueName('QA_Delete_Login');
    const email = `${name.toLowerCase()}@example.com`;
    const password = 'Passw0rd123';
    await addCompanyButton().click();
    await companyNameField().waitForDisplayed({ timeout: 10000 });
    await companyNameField().setValue(name);
    await companyEmailField().setValue(email);
    await companyPasswordField().setValue(password);
    await companySaveButton().click();
    await driver.waitUntil(async () => !(await companyNameField().isDisplayed().catch(() => false)), { timeout: 15000 });

    await searchOnCompaniesScreen(name);
    await openRowContextMenu(name, 'Delete');
    const confirmYes = driver.$('~Yes');
    const hasConfirm = await confirmYes.waitForDisplayed({ timeout: 4000 }).then(() => true).catch(() => false);
    if (hasConfirm) await confirmYes.click();
    await driver.pause(2000);

    await searchOnCompaniesScreen(name);
    const stillListed = await rowEl(name).isDisplayed().catch(() => false);
    assert.strictEqual(stillListed, false, 'Expected the deleted company to no longer be listed');

    await ensureLoggedOut();
    await fillLoginForm(email, password);
    await driver.pause(3000);
    const reachedDashboard = await dashboardProductsShortcut().isDisplayed().catch(() => false);
    console.log(`TC40: after deleting "${name}" and logging in with its own credentials - reachedDashboard=${reachedDashboard}`);
    assert.strictEqual(reachedDashboard, false, 'A deleted company should not be able to log in at all');
  });

  it('TC41: Staff ka "Allow to Login" off karne se uska apna login block ho jata hai, wapas on karne se restore ho jata hai', async () => {
    await goToStaffScreen();
    await staffSearchField().waitForDisplayed({ timeout: 10000 });
    await staffSearchField().setValue('irfan');
    await driver.pause(1500);
    await driver.execute('mobile: hideKeyboard').catch(() => {});
    await toggleAllowToLogin();

    await ensureLoggedOut();
    await fillLoginForm(STAFF_EMAIL, STAFF_PASSWORD);
    await driver.pause(3000);
    const blockedReachedDashboard = await dashboardProductsShortcut().isDisplayed().catch(() => false);
    const onSelectCompany = await selectCompanySearchField().isDisplayed().catch(() => false);
    console.log(`TC41: after "Allow to Login" OFF, staff login - reachedDashboard=${blockedReachedDashboard}, onSelectCompany=${onSelectCompany}`);

    // Restore regardless of the assertion outcome so later runs / other tests are not affected.
    await goToStaffScreen();
    await staffSearchField().waitForDisplayed({ timeout: 10000 });
    await staffSearchField().setValue('irfan');
    await driver.pause(1500);
    await driver.execute('mobile: hideKeyboard').catch(() => {});
    await toggleAllowToLogin();

    assert.strictEqual(blockedReachedDashboard, false, 'Staff login should be blocked while "Allow to Login" is off');
  });

  it('TC41b: "Allow to Login" wapas on karne ke baad staff dobara login kar pata hai (restore verification)', async () => {
    await loginAndSelectCompany(STAFF_EMAIL, STAFF_PASSWORD, SUB_COMPANY_2);
    assert.ok(await dashboardProductsShortcut().isDisplayed());
  });

  it('TC42: Staff Delete karne se wo Staff list se hat jata hai', async () => {
    await goToStaffScreen();
    await staffSearchField().waitForDisplayed({ timeout: 10000 });
    await staffSearchField().setValue('QA_AccessTest');
    await driver.pause(1500);
    await driver.execute('mobile: hideKeyboard').catch(() => {});
    // The search box itself contains the same text, so target the row's TextView only.
    const row = driver.$('android=new UiSelector().textContains("QA_AccessTest").className("android.widget.TextView")');
    const stillPresent = await row.isDisplayed().catch(() => false);
    if (!stillPresent) {
      console.log('TC42: no leftover QA_AccessTest staff found (may already be deleted from a previous run) - skipping.');
      return;
    }
    const rowText = await row.getText();
    await openRowContextMenu(rowText, 'Delete');
    const confirmYes = driver.$('~Yes');
    const hasConfirm = await confirmYes.waitForDisplayed({ timeout: 4000 }).then(() => true).catch(() => false);
    if (hasConfirm) await confirmYes.click();
    await driver.pause(2000);

    await staffSearchField().waitForDisplayed({ timeout: 10000 });
    await staffSearchField().setValue('QA_AccessTest');
    await driver.pause(1500);
    const stillListed = await driver.$('android=new UiSelector().textContains("QA_AccessTest").className("android.widget.TextView")').isDisplayed().catch(() => false);
    assert.strictEqual(stillListed, false, 'Expected the deleted staff member to no longer be listed');
  });
});
